services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: 6297747001:AAHSdTC8IPEIhGW9fIt8M7hEbZQkGEG__98
